#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'chef-client'
cookbook 'build-essential'
cookbook 'apt'

cookbook 'rvm', :git => 'git://github.com/fnichol/chef-rvm.git'
cookbook 'rvm_passenger', :git => 'https://github.com/fnichol/chef-rvm_passenger'
cookbook 'nginx'
